apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-dev1
  namespace: php-app-dev1
spec:
  template:
    spec:
      initContainers:
        - name: init-data
          volumeMounts:
            - name: data-volume
              mountPath: /mnt/shared
              subPath: dev1
      containers:
        - name: php-app
          volumeMounts:
            - name: data-volume
              mountPath: /var/www/html/config/test.txt
              subPath: dev1/config/test.txt
